Repository n-air-app/n-air-app, pull requests merged in 2018-08, with the labels that each got.

#10 use obs-studio-node v0.0.47 instead of v0.0.48
  package.json
  yarn.lock
Labels: enhancement

#32 ニコニコ未ログイン時、配信設定のURLとストリームキーを起動時に消さないように修正
  app/services/settings/settings.ts
Labels: bug

#45 頂点にあるリサイズボックスでもクロップ可能にする
  app/components/StudioEditor.vue.ts
  app/util/ScalableRectangle.ts
Labels: streamlabs

#47 アイテムのリサイズ時にディスプレイ倍率が1以外の環境でずれる問題を修正
  app/components/StudioEditor.vue.ts
Labels: bug, streamlabs
