Repository n-air-app/n-air-app, pull requests merged in 2018-11, with the labels that each got.

#115 ログイン中に配信を開始して番組がないと返ってきたら1回だけリトライする
  app/components/StartStreamingButton.vue
  app/components/StartStreamingButton.vue.ts
  app/i18n/en-US/streaming.json
  app/i18n/ja-JP/streaming.json
  app/services/platforms/niconico.test.ts
  app/services/platforms/niconico.ts
  app/services/streaming/streaming-api.ts
  app/services/streaming/streaming.ts
  app/util/sleep.ts
Labels: niconico

#190 音声ミュートをしているときはもう少し表示をはっきり分かるようにしたい
  app/components/MixerItem.vue
  app/components/shared/Slider.vue
  app/styles/_colors.less
Labels: design work

#191 修正: ニコニコ生放送最適化の設定書き込みを確実にするためにリトライする
  app/components/windows/OptimizeForNiconico.vue.ts
  app/services/settings/optimizer.ts
  app/services/settings/settings.ts
  app/services/streaming/streaming.ts
Labels: bug, development, niconico

#192 CIでユニットテストを実行＆StreamingServiceにユニットテストを書く
  app/services/streaming/streaming.test.ts
  appveyor.yml
  package.json
  yarn.lock
Labels: development

#194 修正: リリーススクリプトで GitHubにアップロード時の切断エラーをリトライする
  bin/mini-release.js
Labels: development

#202 better sentry log message of optimization status
  app/services/settings/settings.ts
Labels: development
