Repository n-air-app/n-air-app, pull requests merged in 2019-11, with the labels that each got.

#387 録画開始時にSentryに録画種別を送信する
  app/services/settings/settings.ts
  app/services/streaming/streaming.ts
Labels: development, niconico

#394 初期状態でシーンコレクションにサンプルを登録する
  app/components/SceneSelector.vue
  app/components/SceneSelector.vue.ts
  app/i18n/en-US/scenes.json
  app/i18n/ja-JP/scenes.json
  app/services/dismissables.ts
  app/services/scene-collections/scene-collections.ts
  app/services/scene-collections/state.ts
  electron-builder/stable.config.js
  scene-presets/basic.json
  scene-presets/basic/images/nair-preset-background.png
  scene-presets/basic/images/nair-preset-bilibili.png
  scene-presets/basic/images/nair-preset-fukidashi.png
  scene-presets/basic/images/nair-preset-twitter.png
  test/api/audio.ts
  test/api/scenes.ts
  test/api/selection.ts
  test/api/sources.ts
  test/e2e/scenes.js
  test/helpers/spectron/scenes.js
Labels: niconico

#395 ソースプリセット(#394)の修正
  app/services/dismissables.ts
  scene-presets/basic.json
Labels: bug, niconico

#398 更新: TypeScript 3.7系を使用
  package.json
  yarn.lock
Labels: development

#397 修正:初回起動時に OBS Importしたときにシーンプリセットのバルーンが取り残される問題
  app/services/scene-collections/scene-collections.ts
Labels: bug, niconico

#379 修正: エンコーダー名の変更を反映
  app/i18n/en-US/settings.json
  app/i18n/ja-JP/settings.json
Labels: translation issue, unstable

#388 修正:リリーススクリプト:前バージョン情報取得元をタグからpackage.jsonに変更
  bin/release/configs/type.d.ts
  bin/release/generatePatchNote.js
  bin/release/mini-release.js
  bin/release/scripts/patchNote.js
  bin/release/scripts/patchNote.test.js
  package.json
Labels: development

#399 修正: 初回プリセット設定時にデフォルト音声ソースが消えないようにする
  app/services/scene-collections/scene-collections.ts
Labels: bug, niconico
