Repository n-air-app/n-air-app, pull requests merged in 2019-04, with the labels that each got.

#257 開閉ボタンにスタイルを適用
  app/components/nicolive-area/NicoliveArea.vue
  app/components/nicolive-area/NicoliveArea.vue.ts
  media/images/controls-arrow-vertical.svg
Labels: design work

#253 コメントフォームにスタイルを適用
  app/components/nicolive-area/CommentForm.vue
  app/styles/_colors.less
Labels: design work

#258 トップナビにスタイルを適用
  app/components/nicolive-area/TopNav.vue
  app/fonts/glyphs/edit.svg
  app/fonts/glyphs/reload.svg
  app/fonts/n-air.woff
  app/styles/custom-icons.less
  bin/yarn.lock
Labels: design work

#267 ツールバーにスタイルを適用
  app/components/nicolive-area/ToolBar.vue
  app/components/nicolive-area/ToolBar.vue.ts
  app/fonts/glyphs/manual-extention.svg
  app/fonts/n-air.woff
  app/styles/custom-icons.less
  app/styles/inputs.less
Labels: design work

#268 番組情報エリアにスタイルを適用
  app/components/nicolive-area/ProgramInfo.vue
  app/components/nicolive-area/ProgramInfo.vue.ts
  app/styles/_colors.less
  app/styles/buttons.less
Labels: design work

#264 変更: 自動延長状態を永続化
  app/services-manager.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/nicolive-program/state.ts
Labels: niconico

#265 変更: ニコ生エリアの開閉状態を永続化
  app/components/nicolive-area/NicoliveArea.vue.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/nicolive-program/state.ts
Labels: niconico

#266 変更: ニコ生パネルの開閉に応じてウィンドウ幅を変更
  app/services/__mocks__/stateful-service.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/persistent-stateful-service.ts
  app/services/streaming/streaming.ts
Labels: niconico

#274 番組詳細エリアにスタイルを適用
  app/components/nicolive-area/ProgramDescription.vue
  app/components/nicolive-area/ProgramDescription.vue.ts
  app/styles/_colors.less
Labels: design work, niconico

#177 変更: niconico最適化を出力:基本に変更し、NVENC/QSVがあれば選択する
  app/i18n/en-US/settings.json
  app/i18n/ja-JP/settings.json
  app/services/settings/__snapshots__/optimizer.test.ts.snap
  app/services/settings/niconico-optimization.ts
  app/services/settings/optimizer.test.ts
  app/services/settings/optimizer.ts
  app/services/settings/settings.ts
  yarn.lock
Labels: niconico

#278 修正: 手動延長ボタンが押せない状態の見た目修正
  app/components/nicolive-area/ToolBar.vue
Labels: bug, design work, niconico

#279 修正: 予約時のボタンのラベルとカラーの修正
  app/components/nicolive-area/ProgramInfo.vue
  app/styles/buttons.less
Labels: design work, niconico

#280 追加: 配信ページ・配信コミュニティへのリンクを追加
  app/components/nicolive-area/ProgramInfo.vue
  app/components/nicolive-area/ProgramInfo.vue.ts
Labels: niconico

#283 修正: 見た目の修正
  app/components/nicolive-area/ProgramStatistics.vue
  app/components/nicolive-area/ToolBar.vue
  app/styles/inputs.less
Labels: bug, design work, niconico

#286 修正: 配信時間表示が一瞬異常な値になる問題を修正、他
  app/components/nicolive-area/ToolBar.vue.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: bug, niconico

#281 修正: 番組情報の変化をツールチップに反映
  app/components/nicolive-area/ProgramInfo.vue
  app/components/nicolive-area/ProgramInfo.vue.ts
Labels: niconico

#270 変更: ログアウトしたら番組情報をクリアする
  app/services/nicolive-program/nicolive-program.ts
Labels: niconico

#275 変更: メンテ中の作成画面にあるインフォへのリンクを踏めるようにする
  app/services/nicolive-program/NicoliveClient.ts
Labels: niconico

#287 修正: ログアウト防止が動作するように
  app/services/nicolive-program/NicoliveClient.ts
Labels: bug, niconico

#290 番組詳細で英文が折り返されないバグの修正
  app/components/nicolive-area/NicoliveArea.vue
  app/components/nicolive-area/ProgramDescription.vue
Labels: bug, design work, niconico

#276 追加: エラーダイアログを実装
  app/components/nicolive-area/CommentForm.vue.ts
  app/components/nicolive-area/NicoliveArea.vue.ts
  app/components/nicolive-area/ProgramInfo.vue.ts
  app/components/nicolive-area/ToolBar.vue.ts
  app/components/nicolive-area/TopNav.vue.ts
  app/i18n/en-US/nicolive-program.json
  app/i18n/ja-JP/nicolive-program.json
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: niconico

#291 修正: 運営コメントフォームの動作を調整
  app/components/nicolive-area/CommentForm.vue
  app/components/nicolive-area/CommentForm.vue.ts
Labels: bug, niconico

#288 修正: テキスト編集中にショートカットキーが誤爆している
  app/services/shortcuts.ts
Labels: bug, streamlabs

#293 修正: 運営コメント送信時の400エラーに対応する文言を追加
  app/i18n/en-US/nicolive-program.json
  app/i18n/ja-JP/nicolive-program.json
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: niconico
