Repository n-air-app/n-air-app, pull requests merged in 2019-06, with the labels that each got.

#315 追加: 最適化ダイアログにハードウェアエンコーダを使うかどうかのオプションを追加
  app/components/ExtraSettings.vue
  app/components/ExtraSettings.vue.ts
  app/components/windows/NicoliveProgramSelector.vue.ts
  app/components/windows/OptimizeForNiconico.vue
  app/components/windows/OptimizeForNiconico.vue.ts
  app/i18n/en-US/settings.json
  app/i18n/en-US/streaming.json
  app/i18n/ja-JP/settings.json
  app/i18n/ja-JP/streaming.json
  app/services/customization/customization-api.ts
  app/services/customization/customization.ts
  app/services/settings/niconico-optimization.ts
  app/services/settings/optimizer.ts
  app/services/settings/settings.ts
  app/services/streaming/streaming.test.ts
  app/services/streaming/streaming.ts
Labels: niconico

#316 最適化ダイアログから「今後、このダイアログを表示しない」 チェックボックスが消えていたので復活
  app/services/streaming/streaming.ts
Labels: bug, niconico

#319 リリーススクリプトの依存更新: update @octokit/rest to 16.28.1
  bin/mini-release.js
  bin/package.json
  bin/yarn.lock
Labels: development

#320 インフラの構成変更に伴いインストーラなどのS3へのアップロードパスを変更
  bin/mini-release.js
Labels: development
