Repository n-air-app/n-air-app, pull requests merged in 2020-03, with the labels that each got.

#437 変更: キャッシュIDをSentryに送信
  app/services/questionaire.ts
  app/services/user.ts
Labels: development, enhancement

#434 追加: SSNG操作時のエラーメッセージを追加
  app/components/nicolive-area/CommentFilter.vue.ts
  app/i18n/en-US/nicolive-program.json
  app/i18n/ja-JP/nicolive-program.json
  app/services/nicolive-program/nicolive-comment-filter.test.ts
  app/services/nicolive-program/nicolive-comment-filter.ts
Labels: enhancement, niconico, translation issue

#439 add clipboard menu on login page
  app/services/settings/optimizer.test.ts
  app/services/user.ts
Labels: enhancement

#440 クリップボードメニューを番組作成・編集画面にも追加する
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/nicolive-comment-filter.test.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/user.ts
  app/util/addClipboardMenu.ts
Labels: niconico
