Repository n-air-app/n-air-app, pull requests merged in 2020-02, with the labels that each got.

#423 ニコ生エリアのデザイン調整
  app/components/nicolive-area/AreaSwitcher.vue
  app/components/nicolive-area/CommentForm.vue
  app/components/nicolive-area/CommentViewer.vue
  app/components/nicolive-area/NicoliveArea.vue
  app/components/nicolive-area/ProgramDescription.vue
  app/components/nicolive-area/ProgramInfo.vue
  app/components/nicolive-area/ProgramStatistics.vue
  app/components/nicolive-area/ToolBar.vue
  app/fonts/glyphs/extention.svg
  app/fonts/n-air.woff
  app/styles/classes.less
  app/styles/custom-icons.less
  app/styles/inputs.less
  app/styles/mixins.less
Labels: design work

#424 放送者NG設定のスタイル実装
  app/components/nicolive-area/CommentFilter.vue
  app/components/nicolive-area/CommentFilter.vue.ts
  app/components/nicolive-area/CommentLocalFilter.vue
  app/components/nicolive-area/CommentViewer.vue
  app/components/nicolive-area/ProgramStatistics.vue
Labels: design work

#431 add scope parameter to login URL
  app/services/hosts.ts
Labels: niconico

#433 変更: エラーコードもエラーダイアログに表示する
  app/services/nicolive-program/NicoliveFailure.ts
Labels: enhancement, niconico

#435 変更: 4xx、5xxのエラーで文言未定義の場合に400、500にフォールバックする
  app/services/nicolive-program/NicoliveFailure.test.ts
  app/services/nicolive-program/NicoliveFailure.ts
Labels: enhancement, niconico
