Repository n-air-app/n-air-app, pull requests merged in 2023-08, with the labels that each got.

#680 fix: アップデート画面（ダウンロード）の修正
  updater/UpdaterWindow.vue
Labels: design work

#670 WIP: Feature/nameplate
  .vscode/settings.json
  app/app-services.ts
  app/components/CommentSettings.vue
  app/components/nicolive-area/CommentViewer.vue
  app/components/nicolive-area/CommentViewer.vue.ts
  app/components/nicolive-area/comment/CommentBase.ts
  app/components/nicolive-area/comment/CommonComment.vue
  app/components/nicolive-area/comment/CommonComment.vue.ts
  app/components/nicolive-area/comment/EmotionComment.vue
  app/components/nicolive-area/comment/GiftComment.vue
  app/components/nicolive-area/comment/NicoadComment.vue
  app/components/nicolive-area/comment/SystemMessage.vue
  app/components/nicolive-area/comment/comment.less
  app/components/windows/UserInfo.vue
  app/components/windows/UserInfo.vue.ts
  app/fonts/glyphs/follow.svg
  app/fonts/n-air.woff
  app/services/nicolive-program/ChatMessage.ts
  app/services/nicolive-program/ChatMessage/getDisplayName.ts
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/ResponseTypes.ts
  app/services/nicolive-program/konomi-tags.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/nicolive-program/state.ts
  app/services/windows.ts
  app/styles/_colors.less
  app/styles/custom-icons.less
  package.json
  yarn.lock
Labels: enhancement, niconico

#693 開発: リリーススクリプトがGitHub Releaseを作ったときにSlackに報告する
  bin/package.json
  bin/release/mini-release.js
  bin/yarn.lock
Labels: development

#699 修正: Sentryにたまに来ている RecRB of undefined エラーを修正
  app/components/StreamingController.vue.ts
Labels: bug
