Repository n-air-app/n-air-app, pull requests merged in 2024-03, with the labels that each got.

#730 Bump @sentry/cli to 2.30.2
  bin/package.json
  bin/yarn.lock
Labels: development

#729 rtvcライブラリを1.0.4に更新
  scripts/install-native-deps.js
Labels: Voice Changer

#731 開発: CI(test)を GitHub Actionsで実行する
  .github/dependabot.yml
  .github/workflows/test.yml
  appveyor.yml
  package.json
Labels: development

#732 appveyor.ymlを削除し、README.mdのBuild status badgeもGitHub Actionsのものに変更
  README.md
  appveyor.yml
Labels: development

#735 修正: 放送者NG上限表示を一般会員もプレミアム会員と同じ500に
  app/components/nicolive-area/CommentFilter.vue.ts
Labels: bug, niconico
