Repository n-air-app/n-air-app, pull requests merged in 2024-09, with the labels that each got.

#807 追加: 「棒読みちゃん」のような外部ツールにHTTP連携でコメントを送信する機能
  app/components/CommentSettings.vue
  app/components/CommentSettings.vue.ts
  app/components/nicolive-area/CommentViewer.vue.ts
  app/components/windows/Settings.vue
  app/services/nicolive-program/NdgrCommentReceiver.ts
  app/services/nicolive-program/httpRelation.test.ts
  app/services/nicolive-program/httpRelation.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/nicolive-program/state.ts
  app/services/streaming/streaming.ts
Labels: enhancement, niconico

#820 開発: @sentry/electron を 5.4.0に上げる
  app/app.ts
  package.json
  yarn.lock
Labels: development

#821 開発: obs-studio-nodeのバージョンをSentry tagに付ける
  main.js
Labels: development

#823 追加: コンパクトモード時にウィンドウを最前面にする設定
  app/components/ExtraSettings.vue
  app/components/ExtraSettings.vue.ts
  app/components/SideNav.vue
  app/i18n/en-US/settings.json
  app/i18n/ja-JP/settings.json
  app/services/customization/customization-api.ts
  app/services/customization/customization.ts
  app/services/nicolive-program/state.ts
  app/services/window-size.test.ts
  app/services/window-size.ts
Labels: enhancement, niconico

#825 追加: 読み上げ有効時、番組が終了したときに「番組が終了しました」と読み上げる
  app/components/nicolive-area/CommentViewer.vue
  app/components/nicolive-area/CommentViewer.vue.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: niconico

#826 修正: 番組自動終了時にコメントリストを消さないようにする
  app/services/nicolive-program/nicolive-comment-viewer.ts
Labels: bug, niconico

#828 修正: N Airの外で番組を終了させたときにもN Airの番組状態に即時反映する
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
Labels: niconico

#830 開発: momentからluxonに移行する
  .vscode/settings.json
  app/app.ts
  app/components/EditableSceneCollection.vue.ts
  app/components/NotificationsArea.vue.ts
  app/components/nicolive-area/ProgramInfo.vue.ts
  app/components/windows/Informations.vue.ts
  app/components/windows/Notifications.vue.ts
  app/components/windows/Troubleshooter.vue.ts
  app/services/scene-collections/scene-collections-api.ts
  app/services/scene-collections/state.ts
  app/services/sources/sources.ts
  app/services/streaming/streaming.ts
  app/services/windows.ts
  bin/package.json
  bin/release/scripts/patchNote.js
  bin/release/scripts/patchNote.test.js
  bin/yarn.lock
  package.json
  yarn.lock
Labels: development

#827 修正: PCの時計がずれているときにサーバーの時計を使って補正表示する
  app/components/nicolive-area/ToolBar.vue.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: niconico

#749 開発: Bump typescript from 4.9.5 to 5.5.4
  app/components/ApiSettings.vue.ts
  app/components/AppearanceSettings.vue.ts
  app/components/NotificationsSettings.vue.ts
  app/components/SourceSelector.vue.ts
  app/components/StudioEditor.vue.ts
  app/components/obs/inputs/Components.ts
  app/components/obs/inputs/ObsFontInput.vue.ts
  app/components/obs/inputs/ObsTextInput.vue.ts
  app/components/shared/inputs/BaseInput.ts
  app/components/tsx-component.ts
  app/services-manager.ts
  app/services/api/external-api.ts
  app/services/api/internal-api-client.ts
  app/services/api/rpc-api.ts
  app/services/audio/audio.ts
  app/services/core/service.ts
  app/services/core/stateful-service.ts
  app/services/dismissables.ts
  app/services/i18n/i18n.ts
  app/services/nicolive-program/NdgrCommentReceiver.ts
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/speech/NVoiceClient.ts
  app/services/obs-api.ts
  app/services/obs-importer.ts
  app/services/patch-notes/index.ts
  app/services/performance/performance.ts
  app/services/protocol-links.ts
  app/services/scene-collections/nodes/hotkeys.ts
  app/services/scene-collections/nodes/overlays/nvoice-character.ts
  app/services/scene-collections/nodes/overlays/video.ts
  app/services/scene-collections/nodes/root.ts
  app/services/scene-collections/nodes/transitions.ts
  app/services/scene-collections/state.ts
  app/services/settings-v2/video.ts
  app/services/settings/optimizer.ts
  app/services/settings/settings.ts
  app/services/sources/sources.ts
  app/services/transitions.ts
  app/services/utils.ts
  app/store/index.ts
  app/util/getKeys.ts
  app/util/profanity.ts
  package.json
  test/helpers/api-client.ts
  test/helpers/modules/forms/form.ts
  test/helpers/webdriver/runner-utils.ts
  test/helpers/webdriver/user.ts
  test/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: development

#831 開発: GitHub Actions: testのe2eテスト/apiを2分割して時間を短縮する
  .github/workflows/test.yml
Labels: development

#834 改善: コメント一覧に切り替えたに最新コメントにスクロールさせる
  app/components/nicolive-area/CommentViewer.vue.ts
Labels: niconico

#835 修正: Windowsの音声合成の再生途中で「再生テスト」などで止めると、以後音声合成が鳴らなくなっていた
  app/components/SpeechEngineSettings.vue.ts
  app/services/nicolive-program/speech/WebSpeechSynthesizer.ts
Labels: bug

#836 開発: CI: paths-filterを使ってコードテスト以外だとtest skip(=succeess)になってbranch protectionを満たすようにする
  .github/workflows/test.yml
Labels: development

#840 開発: 修正:Sentry/開発モードのsourcemapの送り先とeventの送り先を一致させる
  webpack.config.js
Labels: development

#841 開発: Sentry: NdgrClientError まわりを整理
  app/services/nicolive-program/NdgrClient.test.ts
  app/services/nicolive-program/NdgrClient.ts
  app/services/nicolive-program/NdgrFetchError.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-moderators.ts
Labels: development
