Repository n-air-app/n-air-app, pull requests merged in 2024-08, with the labels that each got.

#803 修正: アプリ終了時に番組作成/編集ウィンドウが開いているとそのまま残っていた
  app/services/app/app.ts
  app/services/nicolive-program/NicoliveClient.ts
Labels: niconico

#799 変更: コメントの取得先を新コメントサーバーにする
  .vscode/settings.json
  app/components/nicolive-area/CommentViewer.vue
  app/components/nicolive-area/CommentViewer.vue.ts
  app/components/nicolive-area/comment/CommentBase.ts
  app/components/windows/SourceProperties.vue.ts
  app/components/windows/UserInfo.vue.ts
  app/services/nicolive-program/ChatMessage.ts
  app/services/nicolive-program/ChatMessage/ChatComponentType.ts
  app/services/nicolive-program/ChatMessage/classifier.test.ts
  app/services/nicolive-program/ChatMessage/classifier.ts
  app/services/nicolive-program/ChatMessage/displaytext.ts
  app/services/nicolive-program/ChatMessage/getDisplayName.ts
  app/services/nicolive-program/ChatMessage/util.test.ts
  app/services/nicolive-program/ChatMessage/util.ts
  app/services/nicolive-program/MessageServerClient.ts
  app/services/nicolive-program/NdgrClient.test.ts
  app/services/nicolive-program/NdgrClient.ts
  app/services/nicolive-program/NdgrCommentReceiver.test.ts
  app/services/nicolive-program/NdgrCommentReceiver.ts
  app/services/nicolive-program/NdgrFetchError.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/ResponseTypes.ts
  app/services/nicolive-program/WrappedChat.ts
  app/services/nicolive-program/nicolive-comment-filter.test.ts
  app/services/nicolive-program/nicolive-comment-filter.ts
  app/services/nicolive-program/nicolive-comment-local-filter.ts
  app/services/nicolive-program/nicolive-comment-synthesizer.test.ts
  app/services/nicolive-program/nicolive-comment-synthesizer.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-moderators.test.ts
  app/services/nicolive-program/nicolive-moderators.ts
  app/services/nicolive-program/nicolive-program.test.ts
  app/services/nicolive-program/nicolive-program.ts
  app/services/usage-statistics.ts
  app/util/fakeMode.ts
  package.json
  yarn.lock
Labels: niconico

#805 開発: Sentryに上がっているエラー('offsetWidth' of undefined)修正 / 番組作成・編集ウィンドウからの想定外遷移の記録改善
  app/services/nicolive-program/NicoliveClient.ts
  app/services/patch-notes/index.ts
Labels: niconico, development

#806 開発: onboardingに遷移するときにもSentryに 'offsetWidth' of undefined が出ていたのでこちらも対策
  app/services/onboarding.ts
Labels: development

#809 修正: コメント一覧のギフト・ニコニ広告・エモーションの表示を調整する
  app/components/nicolive-area/comment/GiftComment.vue
  app/components/nicolive-area/comment/NicoadComment.vue
  app/services/nicolive-program/ChatMessage/displaytext.ts
Labels: bug, design work, niconico

#813 開発: Sentryの送信内容を少し改善
  app/services/nicolive-program/NdgrClient.test.ts
  app/services/nicolive-program/NdgrClient.ts
  app/services/nicolive-program/NdgrCommentReceiver.ts
  app/services/nicolive-program/NdgrFetchError.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-moderators.ts
  app/services/nicolive-program/nicolive-program.ts
Labels: development

#815 修正: 今後新しく追加されるシステムメッセージが表示されなくなっていた
  app/services/nicolive-program/ChatMessage.ts
  app/services/nicolive-program/ChatMessage/classifier.test.ts
  app/services/nicolive-program/ChatMessage/classifier.ts
  app/services/nicolive-program/NdgrCommentReceiver.test.ts
  app/services/nicolive-program/NdgrCommentReceiver.ts
Labels: bug, niconico

#817 修正: 画面間ウィンドウ移動時の画面の表示倍率の変化に追従できないことがあった
  app/services/windows.ts
  main.js
Labels: bug

#818 修正: ウィンドウを最小化したり裏に回したりして少し経つとコメントの受信(読み上げ)が止まっていた
  app/services/windows.ts
Labels: bug, niconico

#781 開発: mini-release.js: 再リリース機能(途中でこけたとき用)
  bin/release/mini-release.js
  bin/release/scripts/patchNote.js
  bin/release/scripts/prompt.js
  bin/release/scripts/util.js
Labels: development

#819 修正: コメント一覧に被っていたボタンを邪魔にならない位置に移動
  app/components/nicolive-area/CommentViewer.vue
  app/components/windows/UserInfo.vue
  app/styles/buttons.less
Labels: design work, niconico

#760 追加:サポーターバッジ表示
  .vscode/settings.json
  app/app-services.ts
  app/components/nicolive-area/CommentViewer.vue.ts
  app/components/nicolive-area/comment/CommonComment.vue
  app/components/nicolive-area/comment/CommonComment.vue.ts
  app/components/windows/UserInfo.vue
  app/components/windows/UserInfo.vue.ts
  app/fonts/glyphs/creator-support.svg
  app/fonts/n-air.woff
  app/i18n/en-US/nicolive-program.json
  app/i18n/ja-JP/nicolive-program.json
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/ResponseTypes.ts
  app/services/nicolive-program/WrappedChat.ts
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
  app/services/nicolive-program/nicolive-moderators.test.ts
  app/services/nicolive-program/nicolive-moderators.ts
  app/services/nicolive-program/nicolive-supporters.test.ts
  app/services/nicolive-program/nicolive-supporters.ts
  app/styles/custom-icons.less
  package.json
  yarn.lock
Labels: niconico
