Repository n-air-app/n-air-app, pull requests merged in 2024-04, with the labels that each got.

#736 開発: ボイスチェンジャーのテスト有効化(avaの設定変更)
  package.json
  test/e2e/rtvc.js
Labels: development, Voice Changer

#739 開発:ボイスチェンジャーソースが表示されない環境調査(2)
  app/services/sources/sources.ts
  scripts/install-native-deps.js
  test/tsconfig.json
  tsconfig.json
Labels: bug, Voice Changer

#740 Sentry: 一度出始めると出続けるIPC error送信を削減
  app/app.ts
Labels: development

#738 修正: 放送者NGを配信者用ブロックに文言変更
  app/components/nicolive-area/CommentFilter.vue
  app/components/nicolive-area/CommentViewer.vue.ts
  app/i18n/ja-JP/nicolive-program.json
Labels: niconico

#748 開発: GitHub Actionsのnodeを20.12.1に固定する(現行のe2e testを通すための一時的措置)
  .github/workflows/test.yml
Labels: development

#746 開発: Bump @sentry/electron to 4.23.0
  package.json
  yarn.lock
Labels: development

#753 開発: NicoliveClient クラスのリファクタリング
  app/services/nicolive-program/NicoliveClient.test.ts
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/speech/NVoiceClient.test.ts
Labels: development
