Repository n-air-app/n-air-app, pull requests merged in 2024-10, with the labels that each got.

#842 開発: 開発実行時の i18n missing keysを抑制する
  app/app.ts
  i18n-not-found-keys.txt
  main.js
Labels: development

#843 開発: fix: i18n-not-found-keys.txtの改行文字補正
  main.js
Labels: development

#844 修正: コメントを再読み込みするとブロックしたはずのコメントのブロックが解除されたように見えていた
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
Labels: bug, niconico

#846 修正: 「##このコメントは表示されません##」を読み上げない
  app/services/nicolive-program/nicolive-comment-viewer.test.ts
  app/services/nicolive-program/nicolive-comment-viewer.ts
Labels: bug, niconico

#849 開発: @sentry/electron を5.6.0 に更新
  package.json
  yarn.lock
Labels: development

#852 修正: ニコ生配信最適化でOBS29のNVENCのエンコーダープリセット選択肢の変更に対応(llhq -> p3)
  app/services/settings/niconico-optimization.ts
  app/services/settings/optimizer.ts
Labels: bug, niconico

#855 開発: chore: 未使用のVideoEncodingOptimizationServiceを削除
  app/app-services.ts
  app/services/settings/settings.ts
  app/services/video-encoding-optimizations/definitions.ts
  app/services/video-encoding-optimizations/index.ts
Labels: development

#854 ハードウェア最適化にamdを追加
  app/services/settings/niconico-optimization.test.ts
  app/services/settings/niconico-optimization.ts
  app/services/settings/optimizer.test.ts
  app/services/settings/optimizer.ts
  app/services/streaming/streaming.ts
  app/services/usage-statistics.ts
Labels: niconico

#859 開発: chore: 不要な import electron を削除
  app/components/EditableSceneCollection.vue.ts
  app/components/LanguageSettings.vue.ts
  app/components/Login.vue.ts
  app/components/ModalLayout.vue.ts
  app/components/SceneSelector.vue.ts
  app/components/TitleBar.vue.ts
  app/components/obs/inputs/ObsButtonInput.vue.ts
  app/components/obs/inputs/ObsEditableListInput.vue.ts
  app/components/obs/inputs/ObsPathInput.vue.ts
  app/components/windows/ChildWindow.vue.ts
  app/components/windows/Main.vue.ts
  app/components/windows/OneOffWindow.vue.ts
  app/components/windows/RtvcSourceProperties.vue.ts
  app/services/crash-reporter.ts
  app/services/font-library.ts
  app/services/i18n/i18n.ts
  app/services/key-listener.ts
  app/services/nicolive-program/n-voice-client.ts
  app/services/nvoice-character.ts
  app/services/obs-api.ts
  app/services/obs-importer.ts
  app/services/patch-notes/index.ts
  app/services/performance/performance.ts
  app/services/scene-collections/overlays.ts
  app/services/scene-collections/scene-collections.ts
  app/services/selection/selection.ts
  app/services/sources/monitor-capture-cropping.ts
  app/services/user.ts
  app/services/video.ts
  app/util/DragHandler.ts
  app/util/menus/EditMenu.ts
  app/util/menus/Menu.ts
  updater/ui.js
Labels: development
