Repository n-air-app/n-air-app, pull requests merged in 2025-04, with the labels that each got.

#891 追加: 新規ユーザー向けにヘルプボタンへの誘導のヘルプチップをつける
  app/components/SceneSelector.vue
  app/components/SceneSelector.vue.ts
  app/components/SideNav.vue
  app/components/SideNav.vue.ts
  app/i18n/en-US/common.json
  app/i18n/en-US/scenes.json
  app/i18n/ja-JP/common.json
  app/i18n/ja-JP/scenes.json
  app/services/dismissables.ts
  app/services/scene-collections/scene-collections.ts
  app/services/settings/settings.ts
Labels: enhancement

#914 修正: 左下のログインアイコンをクリックしたときに開くリンクが旧マイページだったのでガレージに修正
  app/services/hosts.ts
Labels: bug, niconico

#909 修正: 0ptのギフト通知が undefinedpt と表示されていた
  app/services/nicolive-program/ChatMessage/displaytext.ts
Labels: bug, niconico

#915 修正: ニコ生パネル開閉ボタンの矢印の向きを反転
  app/components/nicolive-area/NicoliveArea.vue
Labels: niconico

#917 修正: 言語変更などで再起動するときにエラーが出ていた
  main.js
Labels: bug

#908 electron29へのアップデート
  package.json
  yarn.lock
Labels: development

#922 開発: chore: SettingsCategory型を定義して設定に使用
  app/components/windows/Settings.vue.ts
  app/services/protocol-links.ts
  app/services/settings/optimizer.test.ts
  app/services/settings/optimizer.ts
  app/services/settings/settings-api.ts
  app/services/settings/settings.ts
Labels: development
