Repository n-air-app/n-air-app, pull requests merged in 2025-07, with the labels that each got.

#919 修正: 設定の配信タブに表示する警告を分かりやすくしたい
  app/components/obs/inputs/GenericFormGroups.vue
  app/components/obs/inputs/GenericFormGroups.vue.ts
  app/components/windows/Settings.vue
  app/components/windows/Settings.vue.ts
  app/i18n/en-US/settings.json
  app/i18n/ja-JP/settings.json
  app/styles/mixins.less
  app/theme2.less
Labels: niconico

#940 修正: 自動コンパクトモードonでコンパクトモードで終了すると、次回起動時にサイズと位置が通常モードとコンパクトモードで入れ変わってしまっていた
  app/services/compact-mode.ts
  app/services/window-size.test.ts
  app/services/window-size.ts
Labels: bug

#944 開発: ニコ生の配信URL取得APIを更新
  .vscode/settings.json
  app/services/nicolive-program/NicoliveClient.ts
  app/services/nicolive-program/ResponseTypes.ts
  app/services/platforms/niconico.test.ts
  app/services/platforms/niconico.ts
  app/services/streaming/extractPlatform.test.ts
  app/services/streaming/extractPlatform.ts
Labels: niconico

#952 修正: コメント削除の取り消しをしたときにスナックバーを消す
  app/components/nicolive-area/CommentViewer.vue.ts
  app/services/snackbar.ts
Labels: bug, niconico

#953 修正: サブ配信のボタン幅を一部修正
  app/components/SubStreamSettings.vue
Labels: design work
